db_params:
  driver_name: 'pgx'
  user: 'postgres'
  password: '1234'
  db_name: 'billing_db'
  port: '5432'
  ssl_mode: 'disable'
  DATABASE_HOST: 'localhost'
  conn_timeout: 20 #seconds
  conn_retry_interval: 1 # second
app_params:
  base_currency_code: "RUB" # don't change
  db_init_file_path: "./database_data/init_db/init.sql"
  exchange_timeout: 2 #seconds
  request_handle_timeout: 10 #seconds
testing_params:
  db_cleanup_file_path: "./database_data/init_db/clean.sql"
  db_init_file_path: "./database_data/init_db/test_init.sql"
  test_case_timeout: 5 #seconds
log_params:
  log_path: "./log/app_log.log"
  log_level: 2 # WITH INFO, see codes in custom logger package
http_server_params:
  host: 'localhost'
  port: '9000'
  shutdown_timeout: 60 #seconds
  read_timeout: 7 #seconds
  write_timeout: 7 #seconds