version: '3.3'

services:
  database:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: billing_db
    volumes:
      - ./database_data/pgdata:/var/lib/postgresql/data
      - ./database_data/init_db/prod_init:/docker-entrypoint-initdb.d
  cache:
    image: redis:6.0-alpine
    restart: always
    command: redis-server --bind cache --requirepass 1234 --maxmemory 256mb --maxmemory-policy allkeys-lru
  bill_server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_HOST: bill_server
      DATABASE_HOST: database
      CACHE_HOST: cache
    restart: always
    volumes:
      - ./log:/log
    ports:
      - 127.0.0.1:9000:9000
    depends_on:
      - database
      - cache
